version: '3'

services:
  db:
    image: postgres:14.4
    environment: 
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
      args:
        PRIMARY_COLOR: ${PRIMARY_COLOR}
        SECONDARY_COLOR: ${SECONDARY_COLOR}
    volumes:
      - /app/node_modules
      - ./web/:/app
    environment:
      STRAPI_API_URL: ${STRAPI_API_URL}
      STRAPI_PUBLIC_URL: ${STRAPI_URL}
      STRAPI_TOKEN: ${STRAPI_TOKEN}
      MERCHANT_ID: ${PAYTRAIL_MERCHANT_ID}
      SECRET_KEY: ${PAYTRAIL_SECRET_KEY}
      URL: ${URL}
      CALLBACK_URL: ${CALLBACK_URL}
  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile.dev
      args:
        URL: ${STRAPI_URL}
    volumes:
      - /app/node_modules
      - ./cms/:/app
    environment:
      URL: ${STRAPI_URL}
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 1337:1337
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - cms
    ports:
      - 7800:7800