version: '3'

services:
  db:
    image: postgres:14.4
    environment: 
      - POSTGRES_DB=strapi
      - POSTGRES_PASSWORD=strapi
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - default